input {
    kb_layout = gb
    kb_variant = mac      # Apple keyboard layout (fixes Mac key positions)
    follow_mouse = 1
    sensitivity = 0      # -1.0 to 1.0; 0 = no change

    touchpad {
        natural_scroll = true
    }
}

