# ─────────────────────────────────────────────────────────────────────
# PLACEHOLDER — DO NOT USE AS-IS.
#
# This file describes the VM's real disks, filesystems, UUIDs and kernel
# modules, so it can only be generated INSIDE the VM. After you partition
# and mount your disk to /mnt during install, run:
#
#     sudo nixos-generate-config --root /mnt
#
# then copy the generated file over this one:
#
#     cp /mnt/etc/nixos/hardware-configuration.nix \
#        ~/personal-nixos/hosts/vm/hardware-configuration.nix
# ─────────────────────────────────────────────────────────────────────
throw "Replace hosts/vm/hardware-configuration.nix with the file generated by `nixos-generate-config` inside the VM (see comments in this file)."
