//! Generate each tool's theme file from the parsed variables.

use crate::value::{Format, Value};

/// Variable-based tools (eww/waybar/hyprland): dump every variable, so adding
/// one to the config is the only edit needed. GTK CSS @define-color is
/// colours-only, so non-colour values are skipped there.
pub fn vars(vars: &[(String, Value)], f: Format) -> String {
    let mut s = String::from(match f {
        Format::GtkCss => "/* AUTO-GENERATED by theme. Edit theme.conf. */\n",
        _ => "// AUTO-GENERATED by theme. Edit theme.conf.\n",
    });
    for (k, v) in vars {
        if k == "wallpaper" {
            continue;
        }
        match f {
            Format::Scss => s += &format!("${k}: {};\n", v.render(f)),
            Format::Hypr => s += &format!("${k} = {}\n", v.render(f)),
            Format::GtkCss if v.is_color() => s += &format!("@define-color {k} {};\n", v.render(f)),
            _ => {}
        }
    }
    s
}

/// fuzzel/mako have no variable system, so their fixed schema lives here -- the
/// only tool-specific layout in the program. They consume well-known roles.
pub fn fuzzel(vars: &[(String, Value)]) -> String {
    let g = |k: &str| lookup(vars, k, Format::Fuzzel);
    format!(
        "# AUTO-GENERATED by theme. Edit theme.conf.\n\
         [main]\n\
         font={}:size={}\n\
         terminal=ghostty\n\
         prompt=>\n\
         width=40\n\
         lines=12\n\
         \n\
         [colors]\n\
         background={}\n\
         text={}\n\
         selection={}\n\
         selection-text={}\n\
         border={}\n\
         \n\
         [border]\n\
         width={}\n\
         radius={}\n",
        g("font"), g("font_size"), g("bg"), g("text"), g("accent"),
        g("base"), g("accent"), g("border"), g("radius"),
    )
}

pub fn mako(vars: &[(String, Value)]) -> String {
    let g = |k: &str| lookup(vars, k, Format::Mako);
    format!(
        "# AUTO-GENERATED by theme. Edit theme.conf.\n\
         font={} {}\n\
         background-color={}\n\
         text-color={}\n\
         border-color={}\n\
         border-size={}\n\
         border-radius={}\n\
         padding=10\n\
         margin=10\n\
         default-timeout=5000\n",
        g("font"), g("font_size"), g("bg"), g("text"), g("accent"),
        g("border"), g("radius"),
    )
}

fn lookup(vars: &[(String, Value)], key: &str, f: Format) -> String {
    vars.iter()
        .find(|(k, _)| k == key)
        .map(|(_, v)| v.render(f))
        .unwrap_or_default()
}
