#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────
# Regenerates every tool's theme fragment from theme.conf, then reloads.
# Run it with the `theme` command (defined in home/apps/theme.nix).
# This is plain bash — edit it freely; no rebuild needed.
# ─────────────────────────────────────────────────────────────────────
set -euo pipefail

cfg="${XDG_CONFIG_HOME:-$HOME/.config}"
conf="$cfg/theme/theme.conf"

# Parse "key=value" lines (skip comments/blanks) into associative array T.
declare -A T
while IFS='=' read -r k v; do
  key="${k//[[:space:]]/}"
  [[ -z "$key" || "${key:0:1}" == "#" ]] && continue
  T["$key"]="$v"
done < "$conf"

# Opacity percent -> 2-digit hex alpha (for fuzzel/mako, which take #RRGGBBAA).
A="$(printf '%02x' "$(( ${T[opacity]} * 255 / 100 ))")"

# ── COLOUR FORMAT RULES (do not break these) ──────────────────────────
#   eww + waybar (GTK3 CSS) : rgba(r,g,b,a)   NEVER #RRGGBBAA (GTK3 rejects it)
#   mako                    : solid #RRGGBB    NEVER alpha
#   fuzzel                  : RRGGBBAA (no #)  its required native format
#   hyprland                : rgb() / rgba()
# Translucent panel background for the GTK tools, as rgba():
cr=$((16#${T[base]:0:2})); cg=$((16#${T[base]:2:2})); cb=$((16#${T[base]:4:2}))
if [ "${T[opacity]}" -ge 100 ]; then al="1"; else al="0.$(printf '%02d' "${T[opacity]}")"; fi
BG="rgba($cr, $cg, $cb, $al)"

# All colour keys, emitted to the CSS/SCSS fragments.
colors=(base mantle surface surface1 overlay text subtext blue mauve green red yellow peach teal accent accent2)

# ── EWW (SCSS variables) ──
{
  echo "// AUTO-GENERATED by \`theme\` — edit ~/.config/theme/theme.conf instead."
  for c in "${colors[@]}"; do echo "\$$c: #${T[$c]};"; done
  echo "\$bg: $BG;"
  echo "\$radius: ${T[radius]}px;"
  echo "\$border: ${T[border]}px;"
  echo "\$font: \"${T[font]}\";"
} > "$cfg/eww/_theme.scss"

# ── Waybar (GTK @define-color) ──
{
  echo "/* AUTO-GENERATED by \`theme\` — edit ~/.config/theme/theme.conf instead. */"
  for c in "${colors[@]}"; do echo "@define-color $c #${T[$c]};"; done
  echo "@define-color bg $BG;"
} > "$cfg/waybar/colors.css"

# ── Hyprland (variables, sourced first) ──
{
  echo "# AUTO-GENERATED by \`theme\` — edit ~/.config/theme/theme.conf instead."
  echo "\$accent = rgb(${T[accent]})"
  echo "\$accent2 = rgb(${T[accent2]})"
  echo "\$inactive = rgb(${T[surface1]})"
  echo "\$radius = ${T[radius]}"
  echo "\$border_size = ${T[border]}"
  echo "\$gaps_in = ${T[gaps_in]}"
  echo "\$gaps_out = ${T[gaps_out]}"
} > "$cfg/hypr/conf.d/00-theme.conf"

# ── fuzzel (no includes -> whole file regenerated) ──
cat > "$cfg/fuzzel/fuzzel.ini" <<EOF
# AUTO-GENERATED by \`theme\` — edit ~/.config/theme/theme.conf instead.
[main]
font=${T[font]}:size=${T[font_size]}
terminal=ghostty
prompt=>
width=40
lines=12

[colors]
background=${T[base]}$A
text=${T[text]}ff
selection=${T[accent]}ff
selection-text=${T[base]}ff
border=${T[accent]}ff

[border]
width=${T[border]}
radius=${T[radius]}
EOF

# ── mako (no includes -> whole file regenerated) ──
cat > "$cfg/mako/config" <<EOF
# AUTO-GENERATED by \`theme\` — edit ~/.config/theme/theme.conf instead.
font=${T[font]} ${T[font_size]}
background-color=#${T[base]}
text-color=#${T[text]}
border-color=#${T[accent]}
border-size=${T[border]}
border-radius=${T[radius]}
padding=10
margin=10
default-timeout=5000
EOF

# ── reload whatever is currently running (ignore if not) ──
eww reload            >/dev/null 2>&1 || true
pkill -SIGUSR2 waybar >/dev/null 2>&1 || true
hyprctl reload        >/dev/null 2>&1 || true
makoctl reload        >/dev/null 2>&1 || true

echo "✓ theme applied"
